# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-28 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0011_auto_20200928_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_exams',
            name='company_id',
            field=models.CharField(default='', max_length=36),
        ),
    ]
