# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-29 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0014_auto_20200929_1350'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='staff_exams',
            index=models.Index(fields=['company_id', 'staff_id'], name='interview_s_company_dba4de_idx'),
        ),
        migrations.AddIndex(
            model_name='staff_exam_questions',
            index=models.Index(fields=['staff_id', 'exam_id'], name='interview_s_staff_i_1ab7ae_idx'),
        ),
    ]
