# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-29 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0015_auto_20200929_1423'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='staff_exams',
            name='interview_s_company_dba4de_idx',
        ),
        migrations.RemoveIndex(
            model_name='staff_exam_questions',
            name='interview_s_staff_i_1ab7ae_idx',
        ),
        migrations.AlterIndexTogether(
            name='staff_exam_questions',
            index_together=set([('staff_id', 'exam_id')]),
        ),
        migrations.AlterIndexTogether(
            name='staff_exams',
            index_together=set([('company_id', 'staff_id')]),
        ),
    ]
