# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-28 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.CharField(max_length=36)),
                ('title', models.CharField(max_length=36)),
                ('content', models.TextField()),
                ('pass_rate', models.DecimalField(decimal_places=1, max_digits=3)),
                ('level', models.SmallIntegerField(default=0, verbose_name=(0, 1, 2))),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
            ],
        ),
    ]
