# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-28 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffExamQuestions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_id', models.CharField(max_length=36)),
                ('staff_id', models.CharField(max_length=36)),
                ('question_id', models.CharField(max_length=36)),
                ('is_passed', models.SmallIntegerField(default=0, verbose_name=(0, 1))),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StaffExams',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.SmallIntegerField(default=0, verbose_name=(0, 1, 2))),
                ('staff_id', models.CharField(max_length=36)),
                ('is_passed', models.SmallIntegerField(default=0, verbose_name=(0, 1))),
                ('answer_count', models.SmallIntegerField(default=0)),
                ('pass_count', models.SmallIntegerField(default=0)),
                ('total_count', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
            ],
        ),
    ]
