# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-28 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_staffexamquestions_staffexams'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffExamQuestions',
            new_name='Staff_Exam_Questions',
        ),
        migrations.RenameModel(
            old_name='StaffExams',
            new_name='Staff_Exams',
        ),
    ]
