# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-28 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0009_auto_20200928_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='deleted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
