# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-01 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0020_auto_20201001_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='\u5220\u9664\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='staff_exam_questions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='staff_exam_questions',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='\u5220\u9664\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='staff_exam_questions',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='staff_exams',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='staff_exams',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='\u5220\u9664\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='staff_exams',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
    ]
